#!/usr/bin/env node
// Generates the browser-safe quote data from quotes.yaml.
//
// The per-quote pages are handled by VitePress dynamic routes
// (site/quotes/[slug].md + [slug].paths.js) — no markdown files are generated
// by this script. This script only writes quotes.generated.json, which the
// client-side components import:
//   - QuotesIndex.vue  (the searchable index page)
//   - QuoteRef.vue     (inline quote references in notes)
//   - RotatingQuote.vue (home page hero)
//
// The JSON includes the slug and url so components can link to the per-quote
// pages generated by the dynamic routes.
//
// Wired in package.json as `gen:quotes`, run before `dev` and `build`.

import { writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { loadQuotes, slugifyValue } from '../site/quotes/quotes-db.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')
const outPath = join(root, 'site/.vitepress/data/quotes.generated.json')

const quotes = loadQuotes()

// Minimal projection — only the fields the browser components need.
// Author/category slugs and their listing-page URLs are precomputed so the
// index component can link to per-author and per-category pages without
// duplicating the slug logic in the browser.
const data = quotes.map((q) => {
  const authorSlug = slugifyValue(q.author)
  const categorySlug = slugifyValue(q.category)
  return {
    slug: q.slug,
    url: q.url,
    title: q.title,
    text: q.text,
    author: q.author,
    authorSlug,
    authorUrl: `/quotes/by/${authorSlug}`,
    source: q.source,
    category: q.category,
    categorySlug,
    categoryUrl: `/quotes/in/${categorySlug}`,
    circa: q.circa,
    work: q.work,
    context: q.context,
    note: q.note
  }
})

writeFileSync(outPath, JSON.stringify(data, null, 0), 'utf8')
console.log(`Generated quotes.generated.json (${data.length} quotes)`)
